version: "3"

services:
  # RabbitMQ
  rmq:
    container_name: rmq
    hostname: rmq
    build: ./docker/rmq
    image: drsherlock.azurecr.io/image-generator-rmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: drsherlock.azurecr.io/image-generator-api
    command: go run .
    links:
      - rmq
    depends_on:
      - rmq
    ports:
      - "80:80"
